import express from 'express';
import { recordReview } from '../db/reviews.js';
import { logSessionDay } from '../db/streak.js';
import { verifyActionSignature } from '../lib/telegram-digest.js';
import { findUserById } from '../db/auth.js';
import { translator, SUPPORTED_LOCALES } from '../lib/i18n.js';

const router = express.Router();

function confirmText(t) {
    return {
        more: `📈 ${t('telegram.confirm_more')}`,
        less: `📉 ${t('telegram.confirm_less')}`,
        stop: `🚫 ${t('telegram.confirm_stop')}`,
        read: `✅ ${t('telegram.confirm_read')}`,
    };
}

// Tapped from a Telegram digest message -- no login, the signature (derived
// from TELEGRAM_BOT_TOKEN, see lib/telegram-digest.js) is what proves this
// link was generated by us for this exact (user, highlight, action) and
// hasn't been tampered with. 'read' is the one digest-wide link (highlightId
// is the literal string "digest") and the only thing that credits the daily
// streak -- the per-highlight more/less/stop links only affect that
// highlight's review scheduling. This route only needs to be reachable by
// whoever's phone/browser taps the link (normally over Tailscale, same as
// the rest of ReadRepeat) -- unlike inbound file uploads (lib/telegram-
// poller.js), it was never Telegram's own servers calling in, so it doesn't
// need a public endpoint.
router.get('/action/:userId/:highlightId/:action', (req, res) => {
    const { userId, highlightId, action } = req.params;
    const user = findUserById(Number(userId));
    const locale = user?.locale && SUPPORTED_LOCALES.includes(user.locale) ? user.locale : 'nl';
    const t = translator(locale);
    const CONFIRM_TEXT = confirmText(t);
    if (!CONFIRM_TEXT[action]) return res.status(400).send(t('telegram.action_unknown'));
    if (!verifyActionSignature(userId, highlightId, action, req.query.sig)) return res.status(403).send(t('telegram.action_invalid_link'));

    if (action === 'read') {
        logSessionDay(Number(userId));
    } else {
        recordReview(Number(highlightId), action);
    }
    res.send(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>ReadRepeat</title></head>
<body style="font-family:system-ui,sans-serif;max-width:400px;margin:3em auto;padding:0 1.2em;text-align:center;color:#222;">
<p style="font-size:1.3em;">${CONFIRM_TEXT[action]}</p>
<p><a href="/">← ${t('telegram.action_back')}</a></p>
</body></html>`);
});

export default router;
