import crypto from 'crypto';

// Daily "highlights digest" over Telegram -- the self-hosted equivalent of
// Readwise's Daily Review email. One message per day, HTML-formatted, with
// plain signed links per highlight (more/less/never-again) instead of
// Telegram inline buttons -- no webhook/callback plumbing needed, the link
// just hits a public GET route (routes/telegram.js) whose signature proves
// it was generated by us, not guessed. The bot TOKEN is install-wide (one
// bot per ReadRepeat installation, shared across every user of it); WHERE
// to send is per-user (their own telegram_chat_id).
const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
const PUBLIC_BASE_URL = (process.env.PUBLIC_BASE_URL || '').replace(/\/$/, '');

export const telegramDigestConfigured = !!BOT_TOKEN;

// Long-polling (lib/telegram-poller.js) instead of a webhook -- ReadRepeat
// has no public endpoint (Tailscale-only by design), so Telegram can't push
// updates to us.
export async function getTelegramUpdates(offset, timeoutSeconds) {
    const data = await callTelegram('getUpdates', { offset, timeout: timeoutSeconds, allowed_updates: ['message'] });
    return data.result;
}

// Downloads a document a user sent to the bot (Telegram's two-step file
// API: resolve file_id -> file_path, then fetch from the file host). Kindle
// clippings are small plain text, well under any Telegram bot size limit.
export async function downloadTelegramFile(fileId) {
    const info = await callTelegram('getFile', { file_id: fileId });
    const res = await fetch(`https://api.telegram.org/file/bot${BOT_TOKEN}/${info.result.file_path}`);
    if (!res.ok) throw new Error(`telegram_file_download_failed:${res.status}`);
    return res.text();
}

// userId is part of the signed payload (not just routing) so a clicked link
// can credit THAT user's streak (see routes/telegram.js) without letting
// anyone tamper with whose streak gets credited.
function signAction(userId, highlightId, action) {
    return crypto.createHmac('sha256', BOT_TOKEN).update(`${userId}:${highlightId}:${action}`).digest('hex').slice(0, 16);
}

// action must already be one of 'more'/'less'/'stop' -- checked by the route
// before calling this, so a mismatch here just means a wrong/tampered link.
export function verifyActionSignature(userId, highlightId, action, sig) {
    return telegramDigestConfigured && sig && signAction(userId, highlightId, action) === sig;
}

function actionUrl(userId, highlightId, action) {
    return `${PUBLIC_BASE_URL}/telegram/action/${userId}/${highlightId}/${action}?sig=${signAction(userId, highlightId, action)}`;
}

function escapeHtml(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function formatDigest(userId, highlights) {
    const lines = [`📚 <b>${highlights.length} highlight${highlights.length === 1 ? '' : 's'} voor vandaag</b>`];
    for (const h of highlights) {
        lines.push('');
        lines.push(`<b>${escapeHtml(h.book_title)}</b>${h.book_author ? ` — ${escapeHtml(h.book_author)}` : ''}`);
        lines.push(`"${escapeHtml(h.text)}"`);
        if (PUBLIC_BASE_URL) {
            lines.push(
                `<a href="${actionUrl(userId, h.id, 'more')}">📈 Vaker</a> · ` +
                    `<a href="${actionUrl(userId, h.id, 'less')}">📉 Minder</a> · ` +
                    `<a href="${actionUrl(userId, h.id, 'stop')}">🚫 Nooit meer</a>`
            );
        }
    }
    // One link for the whole digest, separate from the per-highlight actions
    // above -- this is the ONLY thing that credits the daily streak (just
    // reading isn't detectable over Telegram, no read receipts), so someone
    // who doesn't want to tune any individual highlight still has a single
    // tap that counts today as reviewed.
    if (PUBLIC_BASE_URL) {
        lines.push('');
        lines.push(`✅ <a href="${actionUrl(userId, 'digest', 'read')}">Markeer als gelezen</a>`);
    }
    return lines.join('\n');
}

async function callTelegram(method, payload) {
    const res = await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/${method}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
    });
    if (!res.ok) throw new Error(`telegram_error:${res.status}:${(await res.text().catch(() => '')).slice(0, 300)}`);
    return res.json();
}

async function sendMessage(chatId, text) {
    await callTelegram('sendMessage', { chat_id: chatId, text, parse_mode: 'HTML', disable_web_page_preview: true });
}

// Exposed for the webhook's import-confirmation reply (routes/telegram.js) --
// same HTML-formatted send as the digest/test messages above.
export const sendTelegramMessage = sendMessage;

export async function sendTelegramDigest(userId, chatId, highlights) {
    if (!BOT_TOKEN) throw new Error('telegram_not_configured');
    await sendMessage(chatId, formatDigest(userId, highlights));
}

export async function sendTelegramTest(chatId) {
    if (!BOT_TOKEN) throw new Error('telegram_not_configured');
    await sendMessage(chatId, '✅ Testbericht van ReadRepeat -- als je dit ziet, werkt de digest-koppeling.');
}
